# This is a basic workflow to help you get started with Actions

name: First work flow

on: workflow_dispatch

jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "hello world"
      - name: print gooodbye
        run: echo "done -bye"
